/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const CommentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ReelId = IDL.Nat;
export const CommentView = IDL.Record({
  'id' : CommentId,
  'isLiked' : IDL.Bool,
  'authorUsername' : IDL.Text,
  'likeCount' : IDL.Nat,
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'author' : UserId,
  'authorAvatarUrl' : IDL.Opt(IDL.Text),
  'authorDisplayName' : IDL.Text,
  'reelId' : ReelId,
});
export const SocialError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
  'cannotFollowSelf' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const UserError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidUsername' : IDL.Null,
  'notFound' : IDL.Null,
  'usernameTaken' : IDL.Null,
});
export const Audience = IDL.Variant({
  'everyone' : IDL.Null,
  'followers' : IDL.Null,
});
export const CreateReelInput = IDL.Record({
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'audience' : Audience,
  'mediaUrl' : IDL.Text,
  'allowComments' : IDL.Bool,
  'caption' : IDL.Text,
  'allowDuet' : IDL.Bool,
  'soundLabel' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const Reel = IDL.Record({
  'id' : ReelId,
  'creator' : UserId,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'audience' : Audience,
  'mediaUrl' : IDL.Text,
  'allowComments' : IDL.Bool,
  'caption' : IDL.Text,
  'allowDuet' : IDL.Bool,
  'soundLabel' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const ReelError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
  'commentsDisabled' : IDL.Null,
});
export const DraftError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const FollowState = IDL.Record({
  'isFollowing' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const ReelView = IDL.Record({
  'id' : ReelId,
  'creator' : UserId,
  'isLiked' : IDL.Bool,
  'likeCount' : IDL.Nat,
  'creatorAvatarUrl' : IDL.Opt(IDL.Text),
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'creatorDisplayName' : IDL.Text,
  'createdAt' : Timestamp,
  'audience' : Audience,
  'creatorUsername' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'allowComments' : IDL.Bool,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
  'allowDuet' : IDL.Bool,
  'soundLabel' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const UserSummary = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'isFollowing' : IDL.Bool,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const Wallet = IDL.Record({
  'referralCode' : IDL.Text,
  'balance' : IDL.Nat,
  'reelEarnings' : IDL.Nat,
  'referralEarnings' : IDL.Nat,
});
export const ActivityKind = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'mention' : IDL.Null,
  'follow' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'commentId' : IDL.Opt(CommentId),
  'preview' : IDL.Opt(IDL.Text),
  'actorAvatarUrl' : IDL.Opt(IDL.Text),
  'kind' : ActivityKind,
  'createdAt' : Timestamp,
  'actorId' : UserId,
  'actorUsername' : IDL.Text,
  'actorDisplayName' : IDL.Text,
  'reelId' : IDL.Opt(ReelId),
});
export const DraftId = IDL.Nat;
export const Draft = IDL.Record({
  'id' : DraftId,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'owner' : UserId,
  'createdAt' : Timestamp,
  'audience' : Audience,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'allowComments' : IDL.Bool,
  'caption' : IDL.Text,
  'allowDuet' : IDL.Bool,
  'soundLabel' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const TransactionId = IDL.Nat;
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionKind = IDL.Variant({
  'reelBonus' : IDL.Null,
  'withdrawal' : IDL.Null,
  'referralBonus' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'status' : TransactionStatus,
  'kind' : TransactionKind,
  'createdAt' : Timestamp,
  'amount' : IDL.Nat,
});
export const WithdrawalRequest = IDL.Record({
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const WalletError = IDL.Variant({
  'insufficientBalance' : IDL.Null,
  'invalidUpiId' : IDL.Null,
  'invalidAmount' : IDL.Null,
});
export const DraftInput = IDL.Record({
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'hashtags' : IDL.Vec(IDL.Text),
  'audience' : Audience,
  'mediaUrl' : IDL.Opt(IDL.Text),
  'allowComments' : IDL.Bool,
  'caption' : IDL.Text,
  'allowDuet' : IDL.Bool,
  'soundLabel' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const SearchFilter = IDL.Variant({
  'all' : IDL.Null,
  'hashtags' : IDL.Null,
  'sounds' : IDL.Null,
  'users' : IDL.Null,
  'reels' : IDL.Null,
});
export const HashtagResult = IDL.Record({
  'tag' : IDL.Text,
  'reelCount' : IDL.Nat,
});
export const SoundResult = IDL.Record({
  'soundLabel' : IDL.Text,
  'reelCount' : IDL.Nat,
});
export const SearchResults = IDL.Record({
  'hashtags' : IDL.Vec(HashtagResult),
  'sounds' : IDL.Vec(SoundResult),
  'users' : IDL.Vec(UserId),
  'reels' : IDL.Vec(ReelId),
});
export const ProfileUpdate = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addComment' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : CommentView, 'err' : SocialError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : UserError })],
      [],
    ),
  'createReel' : IDL.Func(
      [CreateReelInput],
      [IDL.Variant({ 'ok' : Reel, 'err' : ReelError })],
      [],
    ),
  'deleteDraft' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : DraftError })],
      [],
    ),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'follow' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : FollowState, 'err' : SocialError })],
      [],
    ),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowState' : IDL.Func([IDL.Principal], [FollowState], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
  'getReelForCaller' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
  'getReelLikeState' : IDL.Func(
      [IDL.Nat],
      [IDL.Record({ 'isLiked' : IDL.Bool, 'likeCount' : IDL.Nat })],
      ['query'],
    ),
  'getUserSummary' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserSummary)],
      ['query'],
    ),
  'getWallet' : IDL.Func([], [Wallet], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivity' : IDL.Func(
      [IDL.Opt(ActivityKind)],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(CommentView)], ['query']),
  'listDrafts' : IDL.Func([], [IDL.Vec(Draft)], ['query']),
  'listFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'listFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'listFollowingFeed' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
  'listForYouFeed' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
  'listReelsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(ReelView)], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'reelsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'reelsBySound' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'requestWithdrawal' : IDL.Func(
      [WithdrawalRequest],
      [IDL.Variant({ 'ok' : Transaction, 'err' : WalletError })],
      [],
    ),
  'saveDraft' : IDL.Func(
      [IDL.Opt(IDL.Nat), DraftInput],
      [IDL.Variant({ 'ok' : Draft, 'err' : DraftError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'search' : IDL.Func([SearchFilter, IDL.Text], [SearchResults], ['query']),
  'toggleCommentLike' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : SocialError })],
      [],
    ),
  'toggleReelLike' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : SocialError })],
      [],
    ),
  'trendingHashtags' : IDL.Func([IDL.Nat], [IDL.Vec(HashtagResult)], ['query']),
  'unfollow' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : FollowState, 'err' : SocialError })],
      [],
    ),
  'updateProfile' : IDL.Func(
      [ProfileUpdate],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : UserError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const CommentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ReelId = IDL.Nat;
  const CommentView = IDL.Record({
    'id' : CommentId,
    'isLiked' : IDL.Bool,
    'authorUsername' : IDL.Text,
    'likeCount' : IDL.Nat,
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'author' : UserId,
    'authorAvatarUrl' : IDL.Opt(IDL.Text),
    'authorDisplayName' : IDL.Text,
    'reelId' : ReelId,
  });
  const SocialError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
    'cannotFollowSelf' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const UserError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidUsername' : IDL.Null,
    'notFound' : IDL.Null,
    'usernameTaken' : IDL.Null,
  });
  const Audience = IDL.Variant({
    'everyone' : IDL.Null,
    'followers' : IDL.Null,
  });
  const CreateReelInput = IDL.Record({
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'audience' : Audience,
    'mediaUrl' : IDL.Text,
    'allowComments' : IDL.Bool,
    'caption' : IDL.Text,
    'allowDuet' : IDL.Bool,
    'soundLabel' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const Reel = IDL.Record({
    'id' : ReelId,
    'creator' : UserId,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'audience' : Audience,
    'mediaUrl' : IDL.Text,
    'allowComments' : IDL.Bool,
    'caption' : IDL.Text,
    'allowDuet' : IDL.Bool,
    'soundLabel' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const ReelError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
    'commentsDisabled' : IDL.Null,
  });
  const DraftError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const FollowState = IDL.Record({
    'isFollowing' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const ReelView = IDL.Record({
    'id' : ReelId,
    'creator' : UserId,
    'isLiked' : IDL.Bool,
    'likeCount' : IDL.Nat,
    'creatorAvatarUrl' : IDL.Opt(IDL.Text),
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'creatorDisplayName' : IDL.Text,
    'createdAt' : Timestamp,
    'audience' : Audience,
    'creatorUsername' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'allowComments' : IDL.Bool,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
    'allowDuet' : IDL.Bool,
    'soundLabel' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const UserSummary = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'isFollowing' : IDL.Bool,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const Wallet = IDL.Record({
    'referralCode' : IDL.Text,
    'balance' : IDL.Nat,
    'reelEarnings' : IDL.Nat,
    'referralEarnings' : IDL.Nat,
  });
  const ActivityKind = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'mention' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'commentId' : IDL.Opt(CommentId),
    'preview' : IDL.Opt(IDL.Text),
    'actorAvatarUrl' : IDL.Opt(IDL.Text),
    'kind' : ActivityKind,
    'createdAt' : Timestamp,
    'actorId' : UserId,
    'actorUsername' : IDL.Text,
    'actorDisplayName' : IDL.Text,
    'reelId' : IDL.Opt(ReelId),
  });
  const DraftId = IDL.Nat;
  const Draft = IDL.Record({
    'id' : DraftId,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'owner' : UserId,
    'createdAt' : Timestamp,
    'audience' : Audience,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'allowComments' : IDL.Bool,
    'caption' : IDL.Text,
    'allowDuet' : IDL.Bool,
    'soundLabel' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const TransactionId = IDL.Nat;
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionKind = IDL.Variant({
    'reelBonus' : IDL.Null,
    'withdrawal' : IDL.Null,
    'referralBonus' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'status' : TransactionStatus,
    'kind' : TransactionKind,
    'createdAt' : Timestamp,
    'amount' : IDL.Nat,
  });
  const WithdrawalRequest = IDL.Record({
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const WalletError = IDL.Variant({
    'insufficientBalance' : IDL.Null,
    'invalidUpiId' : IDL.Null,
    'invalidAmount' : IDL.Null,
  });
  const DraftInput = IDL.Record({
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'hashtags' : IDL.Vec(IDL.Text),
    'audience' : Audience,
    'mediaUrl' : IDL.Opt(IDL.Text),
    'allowComments' : IDL.Bool,
    'caption' : IDL.Text,
    'allowDuet' : IDL.Bool,
    'soundLabel' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const SearchFilter = IDL.Variant({
    'all' : IDL.Null,
    'hashtags' : IDL.Null,
    'sounds' : IDL.Null,
    'users' : IDL.Null,
    'reels' : IDL.Null,
  });
  const HashtagResult = IDL.Record({ 'tag' : IDL.Text, 'reelCount' : IDL.Nat });
  const SoundResult = IDL.Record({
    'soundLabel' : IDL.Text,
    'reelCount' : IDL.Nat,
  });
  const SearchResults = IDL.Record({
    'hashtags' : IDL.Vec(HashtagResult),
    'sounds' : IDL.Vec(SoundResult),
    'users' : IDL.Vec(UserId),
    'reels' : IDL.Vec(ReelId),
  });
  const ProfileUpdate = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addComment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : CommentView, 'err' : SocialError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : UserError })],
        [],
      ),
    'createReel' : IDL.Func(
        [CreateReelInput],
        [IDL.Variant({ 'ok' : Reel, 'err' : ReelError })],
        [],
      ),
    'deleteDraft' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : DraftError })],
        [],
      ),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'follow' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : FollowState, 'err' : SocialError })],
        [],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowState' : IDL.Func([IDL.Principal], [FollowState], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getReel' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
    'getReelForCaller' : IDL.Func([IDL.Nat], [IDL.Opt(ReelView)], ['query']),
    'getReelLikeState' : IDL.Func(
        [IDL.Nat],
        [IDL.Record({ 'isLiked' : IDL.Bool, 'likeCount' : IDL.Nat })],
        ['query'],
      ),
    'getUserSummary' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserSummary)],
        ['query'],
      ),
    'getWallet' : IDL.Func([], [Wallet], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivity' : IDL.Func(
        [IDL.Opt(ActivityKind)],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'listComments' : IDL.Func([IDL.Nat], [IDL.Vec(CommentView)], ['query']),
    'listDrafts' : IDL.Func([], [IDL.Vec(Draft)], ['query']),
    'listFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'listFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'listFollowingFeed' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
    'listForYouFeed' : IDL.Func([], [IDL.Vec(ReelView)], ['query']),
    'listReelsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReelView)],
        ['query'],
      ),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'reelsByHashtag' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'reelsBySound' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'requestWithdrawal' : IDL.Func(
        [WithdrawalRequest],
        [IDL.Variant({ 'ok' : Transaction, 'err' : WalletError })],
        [],
      ),
    'saveDraft' : IDL.Func(
        [IDL.Opt(IDL.Nat), DraftInput],
        [IDL.Variant({ 'ok' : Draft, 'err' : DraftError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'search' : IDL.Func([SearchFilter, IDL.Text], [SearchResults], ['query']),
    'toggleCommentLike' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : SocialError })],
        [],
      ),
    'toggleReelLike' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : SocialError })],
        [],
      ),
    'trendingHashtags' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HashtagResult)],
        ['query'],
      ),
    'unfollow' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : FollowState, 'err' : SocialError })],
        [],
      ),
    'updateProfile' : IDL.Func(
        [ProfileUpdate],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : UserError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };