/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'commentId' : [] | [CommentId],
  'preview' : [] | [string],
  'actorAvatarUrl' : [] | [string],
  'kind' : ActivityKind,
  'createdAt' : Timestamp,
  'actorId' : UserId,
  'actorUsername' : string,
  'actorDisplayName' : string,
  'reelId' : [] | [ReelId],
}
export type ActivityKind = { 'like' : null } |
  { 'comment' : null } |
  { 'mention' : null } |
  { 'follow' : null };
export type Audience = { 'everyone' : null } |
  { 'followers' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type CommentId = bigint;
export interface CommentView {
  'id' : CommentId,
  'isLiked' : boolean,
  'authorUsername' : string,
  'likeCount' : bigint,
  'createdAt' : Timestamp,
  'text' : string,
  'author' : UserId,
  'authorAvatarUrl' : [] | [string],
  'authorDisplayName' : string,
  'reelId' : ReelId,
}
export interface CreateReelInput {
  'thumbnailUrl' : [] | [string],
  'hashtags' : Array<string>,
  'audience' : Audience,
  'mediaUrl' : string,
  'allowComments' : boolean,
  'caption' : string,
  'allowDuet' : boolean,
  'soundLabel' : [] | [string],
  'location' : [] | [string],
}
export interface Draft {
  'id' : DraftId,
  'thumbnailUrl' : [] | [string],
  'hashtags' : Array<string>,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'audience' : Audience,
  'mediaUrl' : [] | [string],
  'updatedAt' : Timestamp,
  'allowComments' : boolean,
  'caption' : string,
  'allowDuet' : boolean,
  'soundLabel' : [] | [string],
  'location' : [] | [string],
}
export type DraftError = { 'notAuthorized' : null } |
  { 'notFound' : null };
export type DraftId = bigint;
export interface DraftInput {
  'thumbnailUrl' : [] | [string],
  'hashtags' : Array<string>,
  'audience' : Audience,
  'mediaUrl' : [] | [string],
  'allowComments' : boolean,
  'caption' : string,
  'allowDuet' : boolean,
  'soundLabel' : [] | [string],
  'location' : [] | [string],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FollowState {
  'isFollowing' : boolean,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export interface HashtagResult { 'tag' : string, 'reelCount' : bigint }
export interface ProfileUpdate {
  'bio' : [] | [string],
  'username' : [] | [string],
  'displayName' : [] | [string],
  'avatarUrl' : [] | [string],
}
export interface Reel {
  'id' : ReelId,
  'creator' : UserId,
  'thumbnailUrl' : [] | [string],
  'hashtags' : Array<string>,
  'createdAt' : Timestamp,
  'audience' : Audience,
  'mediaUrl' : string,
  'allowComments' : boolean,
  'caption' : string,
  'allowDuet' : boolean,
  'soundLabel' : [] | [string],
  'location' : [] | [string],
}
export type ReelError = { 'notAuthorized' : null } |
  { 'notFound' : null } |
  { 'commentsDisabled' : null };
export type ReelId = bigint;
export interface ReelView {
  'id' : ReelId,
  'creator' : UserId,
  'isLiked' : boolean,
  'likeCount' : bigint,
  'creatorAvatarUrl' : [] | [string],
  'thumbnailUrl' : [] | [string],
  'hashtags' : Array<string>,
  'creatorDisplayName' : string,
  'createdAt' : Timestamp,
  'audience' : Audience,
  'creatorUsername' : string,
  'mediaUrl' : string,
  'allowComments' : boolean,
  'caption' : string,
  'commentCount' : bigint,
  'allowDuet' : boolean,
  'soundLabel' : [] | [string],
  'location' : [] | [string],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SearchFilter = { 'all' : null } |
  { 'hashtags' : null } |
  { 'sounds' : null } |
  { 'users' : null } |
  { 'reels' : null };
export interface SearchResults {
  'hashtags' : Array<HashtagResult>,
  'sounds' : Array<SoundResult>,
  'users' : Array<UserId>,
  'reels' : Array<ReelId>,
}
export type SocialError = { 'notAuthorized' : null } |
  { 'notFound' : null } |
  { 'cannotFollowSelf' : null };
export interface SoundResult { 'soundLabel' : string, 'reelCount' : bigint }
export type Timestamp = bigint;
export interface Transaction {
  'id' : TransactionId,
  'status' : TransactionStatus,
  'kind' : TransactionKind,
  'createdAt' : Timestamp,
  'amount' : bigint,
}
export type TransactionId = bigint;
export type TransactionKind = { 'reelBonus' : null } |
  { 'withdrawal' : null } |
  { 'referralBonus' : null };
export type TransactionStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type UserError = { 'notAuthorized' : null } |
  { 'invalidUsername' : null } |
  { 'notFound' : null } |
  { 'usernameTaken' : null };
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'avatarUrl' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSummary {
  'id' : UserId,
  'username' : string,
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'isFollowing' : boolean,
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Wallet {
  'referralCode' : string,
  'balance' : bigint,
  'reelEarnings' : bigint,
  'referralEarnings' : bigint,
}
export type WalletError = { 'insufficientBalance' : null } |
  { 'invalidUpiId' : null } |
  { 'invalidAmount' : null };
export interface WithdrawalRequest { 'upiId' : string, 'amount' : bigint }
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addComment' : ActorMethod<
    [bigint, string],
    { 'ok' : CommentView } |
      { 'err' : SocialError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<
    [string, string, string, [] | [string]],
    { 'ok' : UserProfile } |
      { 'err' : UserError }
  >,
  'createReel' : ActorMethod<
    [CreateReelInput],
    { 'ok' : Reel } |
      { 'err' : ReelError }
  >,
  'deleteDraft' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : DraftError }
  >,
  'execute' : ActorMethod<[string], Result>,
  'follow' : ActorMethod<
    [Principal],
    { 'ok' : FollowState } |
      { 'err' : SocialError }
  >,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowState' : ActorMethod<[Principal], FollowState>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getProfileByUsername' : ActorMethod<[string], [] | [UserProfile]>,
  'getReel' : ActorMethod<[bigint], [] | [ReelView]>,
  'getReelForCaller' : ActorMethod<[bigint], [] | [ReelView]>,
  'getReelLikeState' : ActorMethod<
    [bigint],
    { 'isLiked' : boolean, 'likeCount' : bigint }
  >,
  'getUserSummary' : ActorMethod<[Principal], [] | [UserSummary]>,
  'getWallet' : ActorMethod<[], Wallet>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivity' : ActorMethod<[[] | [ActivityKind]], Array<Activity>>,
  'listComments' : ActorMethod<[bigint], Array<CommentView>>,
  'listDrafts' : ActorMethod<[], Array<Draft>>,
  'listFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'listFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'listFollowingFeed' : ActorMethod<[], Array<ReelView>>,
  'listForYouFeed' : ActorMethod<[], Array<ReelView>>,
  'listReelsByUser' : ActorMethod<[Principal], Array<ReelView>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'reelsByHashtag' : ActorMethod<[string], Array<bigint>>,
  'reelsBySound' : ActorMethod<[string], Array<bigint>>,
  'requestWithdrawal' : ActorMethod<
    [WithdrawalRequest],
    { 'ok' : Transaction } |
      { 'err' : WalletError }
  >,
  'saveDraft' : ActorMethod<
    [[] | [bigint], DraftInput],
    { 'ok' : Draft } |
      { 'err' : DraftError }
  >,
  'schema' : ActorMethod<[], string>,
  'search' : ActorMethod<[SearchFilter, string], SearchResults>,
  'toggleCommentLike' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : SocialError }
  >,
  'toggleReelLike' : ActorMethod<
    [bigint],
    { 'ok' : boolean } |
      { 'err' : SocialError }
  >,
  'trendingHashtags' : ActorMethod<[bigint], Array<HashtagResult>>,
  'unfollow' : ActorMethod<
    [Principal],
    { 'ok' : FollowState } |
      { 'err' : SocialError }
  >,
  'updateProfile' : ActorMethod<
    [ProfileUpdate],
    { 'ok' : UserProfile } |
      { 'err' : UserError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];