/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Activity {
    id: bigint;
    commentId?: CommentId;
    preview?: string;
    actorAvatarUrl?: string;
    kind: ActivityKind;
    createdAt: Timestamp;
    actorId: UserId;
    actorUsername: string;
    actorDisplayName: string;
    reelId?: ReelId;
}
export interface Cell {
    value: Value;
    name: string;
}
export type CommentId = bigint;
export interface CommentView {
    id: CommentId;
    isLiked: boolean;
    authorUsername: string;
    likeCount: bigint;
    createdAt: Timestamp;
    text: string;
    author: UserId;
    authorAvatarUrl?: string;
    authorDisplayName: string;
    reelId: ReelId;
}
export interface CreateReelInput {
    thumbnailUrl?: string;
    hashtags: Array<string>;
    audience: Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}
export interface Draft {
    id: DraftId;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    owner: UserId;
    createdAt: Timestamp;
    audience: Audience;
    mediaUrl?: string;
    updatedAt: Timestamp;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}
export type DraftId = bigint;
export interface DraftInput {
    thumbnailUrl?: string;
    hashtags: Array<string>;
    audience: Audience;
    mediaUrl?: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface FollowState {
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
}
export interface HashtagResult {
    tag: string;
    reelCount: bigint;
}
export interface ProfileUpdate {
    bio?: string;
    username?: string;
    displayName?: string;
    avatarUrl?: string;
}
export interface Reel {
    id: ReelId;
    creator: UserId;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    createdAt: Timestamp;
    audience: Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}
export type ReelId = bigint;
export interface ReelView {
    id: ReelId;
    creator: UserId;
    isLiked: boolean;
    likeCount: bigint;
    creatorAvatarUrl?: string;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    creatorDisplayName: string;
    createdAt: Timestamp;
    audience: Audience;
    creatorUsername: string;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    commentCount: bigint;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SearchResults {
    hashtags: Array<HashtagResult>;
    sounds: Array<SoundResult>;
    users: Array<UserId>;
    reels: Array<ReelId>;
}
export interface SoundResult {
    soundLabel: string;
    reelCount: bigint;
}
export type Timestamp = bigint;
export interface Transaction {
    id: TransactionId;
    status: TransactionStatus;
    kind: TransactionKind;
    createdAt: Timestamp;
    amount: bigint;
}
export type TransactionId = bigint;
export type UserId = Principal;
export interface UserProfile {
    id: UserId;
    bio: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatarUrl?: string;
}
export interface UserSummary {
    id: UserId;
    username: string;
    displayName: string;
    avatarUrl?: string;
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Wallet {
    referralCode: string;
    balance: bigint;
    reelEarnings: bigint;
    referralEarnings: bigint;
}
export interface WithdrawalRequest {
    upiId: string;
    amount: bigint;
}
export enum ActivityKind {
    like = "like",
    comment = "comment",
    mention = "mention",
    follow = "follow"
}
export enum Audience {
    everyone = "everyone",
    followers = "followers"
}
export enum DraftError {
    notAuthorized = "notAuthorized",
    notFound = "notFound"
}
export enum ReelError {
    notAuthorized = "notAuthorized",
    notFound = "notFound",
    commentsDisabled = "commentsDisabled"
}
export enum SearchFilter {
    all = "all",
    hashtags = "hashtags",
    sounds = "sounds",
    users = "users",
    reels = "reels"
}
export enum SocialError {
    notAuthorized = "notAuthorized",
    notFound = "notFound",
    cannotFollowSelf = "cannotFollowSelf"
}
export enum TransactionKind {
    reelBonus = "reelBonus",
    withdrawal = "withdrawal",
    referralBonus = "referralBonus"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum UserError {
    notAuthorized = "notAuthorized",
    invalidUsername = "invalidUsername",
    notFound = "notFound",
    usernameTaken = "usernameTaken"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WalletError {
    insufficientBalance = "insufficientBalance",
    invalidUpiId = "invalidUpiId",
    invalidAmount = "invalidAmount"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addComment(reelId: bigint, text: string): Promise<{
        __kind__: "ok";
        ok: CommentView;
    } | {
        __kind__: "err";
        err: SocialError;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(username: string, displayName: string, bio: string, avatarUrl: string | null): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: UserError;
    }>;
    createReel(input: CreateReelInput): Promise<{
        __kind__: "ok";
        ok: Reel;
    } | {
        __kind__: "err";
        err: ReelError;
    }>;
    deleteDraft(draftId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: DraftError;
    }>;
    execute(qJson: string): Promise<Result>;
    follow(user: Principal): Promise<{
        __kind__: "ok";
        ok: FollowState;
    } | {
        __kind__: "err";
        err: SocialError;
    }>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getFollowState(user: Principal): Promise<FollowState>;
    getProfile(user: Principal): Promise<UserProfile | null>;
    getProfileByUsername(username: string): Promise<UserProfile | null>;
    getReel(id: bigint): Promise<ReelView | null>;
    getReelForCaller(id: bigint): Promise<ReelView | null>;
    getReelLikeState(reelId: bigint): Promise<{
        isLiked: boolean;
        likeCount: bigint;
    }>;
    getUserSummary(user: Principal): Promise<UserSummary | null>;
    getWallet(): Promise<Wallet>;
    isCallerAdmin(): Promise<boolean>;
    listActivity(kind: ActivityKind | null): Promise<Array<Activity>>;
    listComments(reelId: bigint): Promise<Array<CommentView>>;
    listDrafts(): Promise<Array<Draft>>;
    listFollowers(user: Principal): Promise<Array<Principal>>;
    listFollowing(user: Principal): Promise<Array<Principal>>;
    listFollowingFeed(): Promise<Array<ReelView>>;
    listForYouFeed(): Promise<Array<ReelView>>;
    listReelsByUser(user: Principal): Promise<Array<ReelView>>;
    listTransactions(): Promise<Array<Transaction>>;
    reelsByHashtag(tag: string): Promise<Array<bigint>>;
    reelsBySound(soundLabel: string): Promise<Array<bigint>>;
    requestWithdrawal(request: WithdrawalRequest): Promise<{
        __kind__: "ok";
        ok: Transaction;
    } | {
        __kind__: "err";
        err: WalletError;
    }>;
    saveDraft(draftId: bigint | null, input: DraftInput): Promise<{
        __kind__: "ok";
        ok: Draft;
    } | {
        __kind__: "err";
        err: DraftError;
    }>;
    schema(): Promise<string>;
    search(filter: SearchFilter, term: string): Promise<SearchResults>;
    toggleCommentLike(commentId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: SocialError;
    }>;
    toggleReelLike(reelId: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: SocialError;
    }>;
    trendingHashtags(limit: bigint): Promise<Array<HashtagResult>>;
    unfollow(user: Principal): Promise<{
        __kind__: "ok";
        ok: FollowState;
    } | {
        __kind__: "err";
        err: SocialError;
    }>;
    updateProfile(update: ProfileUpdate): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: UserError;
    }>;
}
import type { Activity as _Activity, ActivityKind as _ActivityKind, Audience as _Audience, Cell as _Cell, CommentId as _CommentId, CommentView as _CommentView, CreateReelInput as _CreateReelInput, Draft as _Draft, DraftError as _DraftError, DraftId as _DraftId, DraftInput as _DraftInput, Error as _Error, FollowState as _FollowState, ProfileUpdate as _ProfileUpdate, Reel as _Reel, ReelError as _ReelError, ReelId as _ReelId, ReelView as _ReelView, Result as _Result, Result__1 as _Result__1, SearchFilter as _SearchFilter, SocialError as _SocialError, Timestamp as _Timestamp, Transaction as _Transaction, TransactionId as _TransactionId, TransactionKind as _TransactionKind, TransactionStatus as _TransactionStatus, UserError as _UserError, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserSummary as _UserSummary, Value as _Value, WalletError as _WalletError } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: CommentView;
    } | {
        __kind__: "err";
        err: SocialError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: UserError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1, arg2, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReel(arg0: CreateReelInput): Promise<{
        __kind__: "ok";
        ok: Reel;
    } | {
        __kind__: "err";
        err: ReelError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createReel(to_candid_CreateReelInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReel(to_candid_CreateReelInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDraft(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: DraftError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDraft(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDraft(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async follow(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: FollowState;
    } | {
        __kind__: "err";
        err: SocialError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.follow(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.follow(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowState(arg0: Principal): Promise<FollowState> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowState(arg0);
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileByUsername(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileByUsername(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileByUsername(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReel(arg0: bigint): Promise<ReelView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReel(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReel(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReelForCaller(arg0: bigint): Promise<ReelView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelForCaller(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelForCaller(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReelLikeState(arg0: bigint): Promise<{
        isLiked: boolean;
        likeCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReelLikeState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReelLikeState(arg0);
            return result;
        }
    }
    async getUserSummary(arg0: Principal): Promise<UserSummary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSummary(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSummary(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(): Promise<Wallet> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivity(arg0: ActivityKind | null): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivity(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivity(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComments(arg0: bigint): Promise<Array<CommentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDrafts(): Promise<Array<Draft>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDrafts();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDrafts();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowers(arg0);
            return result;
        }
    }
    async listFollowing(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowing(arg0);
            return result;
        }
    }
    async listFollowingFeed(): Promise<Array<ReelView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowingFeed();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowingFeed();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listForYouFeed(): Promise<Array<ReelView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listForYouFeed();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listForYouFeed();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReelsByUser(arg0: Principal): Promise<Array<ReelView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReelsByUser(arg0);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReelsByUser(arg0);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async reelsByHashtag(arg0: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.reelsByHashtag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reelsByHashtag(arg0);
            return result;
        }
    }
    async reelsBySound(arg0: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.reelsBySound(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reelsBySound(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: WithdrawalRequest): Promise<{
        __kind__: "ok";
        ok: Transaction;
    } | {
        __kind__: "err";
        err: WalletError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return from_candid_variant_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveDraft(arg0: bigint | null, arg1: DraftInput): Promise<{
        __kind__: "ok";
        ok: Draft;
    } | {
        __kind__: "err";
        err: DraftError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDraft(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0), to_candid_DraftInput_n64(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDraft(to_candid_opt_n63(this._uploadFile, this._downloadFile, arg0), to_candid_DraftInput_n64(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async search(arg0: SearchFilter, arg1: string): Promise<SearchResults> {
        if (this.processError) {
            try {
                const result = await this.actor.search(to_candid_SearchFilter_n67(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.search(to_candid_SearchFilter_n67(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async toggleCommentLike(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: SocialError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCommentLike(arg0);
                return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCommentLike(arg0);
            return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleReelLike(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: SocialError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleReelLike(arg0);
                return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleReelLike(arg0);
            return from_candid_variant_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async trendingHashtags(arg0: bigint): Promise<Array<HashtagResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.trendingHashtags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trendingHashtags(arg0);
            return result;
        }
    }
    async unfollow(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: FollowState;
    } | {
        __kind__: "err";
        err: SocialError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollow(arg0);
                return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollow(arg0);
            return from_candid_variant_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProfile(arg0: ProfileUpdate): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: UserError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n69(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n69(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityKind_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityKind): ActivityKind {
    return "like" in value ? ActivityKind.like : "comment" in value ? ActivityKind.comment : "mention" in value ? ActivityKind.mention : "follow" in value ? ActivityKind.follow : value;
}
function from_candid_Activity_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Audience_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Audience): Audience {
    return "everyone" in value ? Audience.everyone : "followers" in value ? Audience.followers : value;
}
function from_candid_Cell_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CommentView_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommentView): CommentView {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_DraftError_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DraftError): DraftError {
    return "notAuthorized" in value ? DraftError.notAuthorized : "notFound" in value ? DraftError.notFound : value;
}
function from_candid_Draft_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Draft): Draft {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ReelError_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReelError): ReelError {
    return "notAuthorized" in value ? ReelError.notAuthorized : "notFound" in value ? ReelError.notFound : "commentsDisabled" in value ? ReelError.commentsDisabled : value;
}
function from_candid_ReelView_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReelView): ReelView {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Reel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reel): Reel {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SocialError_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialError): SocialError {
    return "notAuthorized" in value ? SocialError.notAuthorized : "notFound" in value ? SocialError.notFound : "cannotFollowSelf" in value ? SocialError.cannotFollowSelf : value;
}
function from_candid_TransactionKind_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionKind): TransactionKind {
    return "reelBonus" in value ? TransactionKind.reelBonus : "withdrawal" in value ? TransactionKind.withdrawal : "referralBonus" in value ? TransactionKind.referralBonus : value;
}
function from_candid_TransactionStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_Transaction_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_UserError_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserError): UserError {
    return "notAuthorized" in value ? UserError.notAuthorized : "invalidUsername" in value ? UserError.invalidUsername : "notFound" in value ? UserError.notFound : "usernameTaken" in value ? UserError.usernameTaken : value;
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_UserSummary_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserSummary): UserSummary {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_WalletError_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletError): WalletError {
    return "insufficientBalance" in value ? WalletError.insufficientBalance : "invalidUpiId" in value ? WalletError.invalidUpiId : "invalidAmount" in value ? WalletError.invalidAmount : value;
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReelView]): ReelView | null {
    return value.length === 0 ? null : from_candid_ReelView_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSummary]): UserSummary | null {
    return value.length === 0 ? null : from_candid_UserSummary_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CommentId]): CommentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReelId]): ReelId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: string;
    username: string;
    displayName: string;
    createdAt: _Timestamp;
    avatarUrl: [] | [string];
}): {
    id: UserId;
    bio: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatarUrl?: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReelId;
    creator: _UserId;
    thumbnailUrl: [] | [string];
    hashtags: Array<string>;
    createdAt: _Timestamp;
    audience: _Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel: [] | [string];
    location: [] | [string];
}): {
    id: ReelId;
    creator: UserId;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    createdAt: Timestamp;
    audience: Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
} {
    return {
        id: value.id,
        creator: value.creator,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.thumbnailUrl)),
        hashtags: value.hashtags,
        createdAt: value.createdAt,
        audience: from_candid_Audience_n22(_uploadFile, _downloadFile, value.audience),
        mediaUrl: value.mediaUrl,
        allowComments: value.allowComments,
        caption: value.caption,
        allowDuet: value.allowDuet,
        soundLabel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.soundLabel)),
        location: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n28(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n32(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReelId;
    creator: _UserId;
    isLiked: boolean;
    likeCount: bigint;
    creatorAvatarUrl: [] | [string];
    thumbnailUrl: [] | [string];
    hashtags: Array<string>;
    creatorDisplayName: string;
    createdAt: _Timestamp;
    audience: _Audience;
    creatorUsername: string;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    commentCount: bigint;
    allowDuet: boolean;
    soundLabel: [] | [string];
    location: [] | [string];
}): {
    id: ReelId;
    creator: UserId;
    isLiked: boolean;
    likeCount: bigint;
    creatorAvatarUrl?: string;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    creatorDisplayName: string;
    createdAt: Timestamp;
    audience: Audience;
    creatorUsername: string;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    commentCount: bigint;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
} {
    return {
        id: value.id,
        creator: value.creator,
        isLiked: value.isLiked,
        likeCount: value.likeCount,
        creatorAvatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.creatorAvatarUrl)),
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.thumbnailUrl)),
        hashtags: value.hashtags,
        creatorDisplayName: value.creatorDisplayName,
        createdAt: value.createdAt,
        audience: from_candid_Audience_n22(_uploadFile, _downloadFile, value.audience),
        creatorUsername: value.creatorUsername,
        mediaUrl: value.mediaUrl,
        allowComments: value.allowComments,
        caption: value.caption,
        commentCount: value.commentCount,
        allowDuet: value.allowDuet,
        soundLabel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.soundLabel)),
        location: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    displayName: string;
    avatarUrl: [] | [string];
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
}): {
    id: UserId;
    username: string;
    displayName: string;
    avatarUrl?: string;
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
} {
    return {
        id: value.id,
        username: value.username,
        displayName: value.displayName,
        avatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.avatarUrl)),
        isFollowing: value.isFollowing,
        followerCount: value.followerCount,
        followingCount: value.followingCount
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    commentId: [] | [_CommentId];
    preview: [] | [string];
    actorAvatarUrl: [] | [string];
    kind: _ActivityKind;
    createdAt: _Timestamp;
    actorId: _UserId;
    actorUsername: string;
    actorDisplayName: string;
    reelId: [] | [_ReelId];
}): {
    id: bigint;
    commentId?: CommentId;
    preview?: string;
    actorAvatarUrl?: string;
    kind: ActivityKind;
    createdAt: Timestamp;
    actorId: UserId;
    actorUsername: string;
    actorDisplayName: string;
    reelId?: ReelId;
} {
    return {
        id: value.id,
        commentId: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.commentId)),
        preview: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.preview)),
        actorAvatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.actorAvatarUrl)),
        kind: from_candid_ActivityKind_n49(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        actorId: value.actorId,
        actorUsername: value.actorUsername,
        actorDisplayName: value.actorDisplayName,
        reelId: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.reelId))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DraftId;
    thumbnailUrl: [] | [string];
    hashtags: Array<string>;
    owner: _UserId;
    createdAt: _Timestamp;
    audience: _Audience;
    mediaUrl: [] | [string];
    updatedAt: _Timestamp;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel: [] | [string];
    location: [] | [string];
}): {
    id: DraftId;
    thumbnailUrl?: string;
    hashtags: Array<string>;
    owner: UserId;
    createdAt: Timestamp;
    audience: Audience;
    mediaUrl?: string;
    updatedAt: Timestamp;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
} {
    return {
        id: value.id,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.thumbnailUrl)),
        hashtags: value.hashtags,
        owner: value.owner,
        createdAt: value.createdAt,
        audience: from_candid_Audience_n22(_uploadFile, _downloadFile, value.audience),
        mediaUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.mediaUrl)),
        updatedAt: value.updatedAt,
        allowComments: value.allowComments,
        caption: value.caption,
        allowDuet: value.allowDuet,
        soundLabel: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.soundLabel)),
        location: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    status: _TransactionStatus;
    kind: _TransactionKind;
    createdAt: _Timestamp;
    amount: bigint;
}): {
    id: TransactionId;
    status: TransactionStatus;
    kind: TransactionKind;
    createdAt: Timestamp;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n59(_uploadFile, _downloadFile, value.status),
        kind: from_candid_TransactionKind_n60(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CommentId;
    isLiked: boolean;
    authorUsername: string;
    likeCount: bigint;
    createdAt: _Timestamp;
    text: string;
    author: _UserId;
    authorAvatarUrl: [] | [string];
    authorDisplayName: string;
    reelId: _ReelId;
}): {
    id: CommentId;
    isLiked: boolean;
    authorUsername: string;
    likeCount: bigint;
    createdAt: Timestamp;
    text: string;
    author: UserId;
    authorAvatarUrl?: string;
    authorDisplayName: string;
    reelId: ReelId;
} {
    return {
        id: value.id,
        isLiked: value.isLiked,
        authorUsername: value.authorUsername,
        likeCount: value.likeCount,
        createdAt: value.createdAt,
        text: value.text,
        author: value.author,
        authorAvatarUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.authorAvatarUrl)),
        authorDisplayName: value.authorDisplayName,
        reelId: value.reelId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: _UserError;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: UserError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_UserError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Reel;
} | {
    err: _ReelError;
}): {
    __kind__: "ok";
    ok: Reel;
} | {
    __kind__: "err";
    err: ReelError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Reel_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ReelError_n23(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _DraftError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: DraftError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_DraftError_n25(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FollowState;
} | {
    err: _SocialError;
}): {
    __kind__: "ok";
    ok: FollowState;
} | {
    __kind__: "err";
    err: SocialError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SocialError_n9(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CommentView;
} | {
    err: _SocialError;
}): {
    __kind__: "ok";
    ok: CommentView;
} | {
    __kind__: "err";
    err: SocialError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CommentView_n6(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SocialError_n9(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transaction;
} | {
    err: _WalletError;
}): {
    __kind__: "ok";
    ok: Transaction;
} | {
    __kind__: "err";
    err: WalletError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Transaction_n57(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WalletError_n62(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Draft;
} | {
    err: _DraftError;
}): {
    __kind__: "ok";
    ok: Draft;
} | {
    __kind__: "err";
    err: DraftError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Draft_n53(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_DraftError_n25(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: _SocialError;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: SocialError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SocialError_n9(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommentView>): Array<CommentView> {
    return value.map((x)=>from_candid_CommentView_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Draft>): Array<Draft> {
    return value.map((x)=>from_candid_Draft_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReelView>): Array<ReelView> {
    return value.map((x)=>from_candid_ReelView_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n57(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityKind_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityKind): _ActivityKind {
    return value == ActivityKind.like ? {
        like: null
    } : value == ActivityKind.comment ? {
        comment: null
    } : value == ActivityKind.mention ? {
        mention: null
    } : value == ActivityKind.follow ? {
        follow: null
    } : value;
}
function to_candid_Audience_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Audience): _Audience {
    return value == Audience.everyone ? {
        everyone: null
    } : value == Audience.followers ? {
        followers: null
    } : value;
}
function to_candid_CreateReelInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateReelInput): _CreateReelInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_DraftInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DraftInput): _DraftInput {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileUpdate_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileUpdate): _ProfileUpdate {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilter_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilter): _SearchFilter {
    return value == SearchFilter.all ? {
        all: null
    } : value == SearchFilter.hashtags ? {
        hashtags: null
    } : value == SearchFilter.sounds ? {
        sounds: null
    } : value == SearchFilter.users ? {
        users: null
    } : value == SearchFilter.reels ? {
        reels: null
    } : value;
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityKind | null): [] | [_ActivityKind] {
    return value === null ? candid_none() : candid_some(to_candid_ActivityKind_n44(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thumbnailUrl?: string;
    hashtags: Array<string>;
    audience: Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}): {
    thumbnailUrl: [] | [string];
    hashtags: Array<string>;
    audience: _Audience;
    mediaUrl: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel: [] | [string];
    location: [] | [string];
} {
    return {
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        hashtags: value.hashtags,
        audience: to_candid_Audience_n18(_uploadFile, _downloadFile, value.audience),
        mediaUrl: value.mediaUrl,
        allowComments: value.allowComments,
        caption: value.caption,
        allowDuet: value.allowDuet,
        soundLabel: value.soundLabel ? candid_some(value.soundLabel) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thumbnailUrl?: string;
    hashtags: Array<string>;
    audience: Audience;
    mediaUrl?: string;
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel?: string;
    location?: string;
}): {
    thumbnailUrl: [] | [string];
    hashtags: Array<string>;
    audience: _Audience;
    mediaUrl: [] | [string];
    allowComments: boolean;
    caption: string;
    allowDuet: boolean;
    soundLabel: [] | [string];
    location: [] | [string];
} {
    return {
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        hashtags: value.hashtags,
        audience: to_candid_Audience_n18(_uploadFile, _downloadFile, value.audience),
        mediaUrl: value.mediaUrl ? candid_some(value.mediaUrl) : candid_none(),
        allowComments: value.allowComments,
        caption: value.caption,
        allowDuet: value.allowDuet,
        soundLabel: value.soundLabel ? candid_some(value.soundLabel) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    username?: string;
    displayName?: string;
    avatarUrl?: string;
}): {
    bio: [] | [string];
    username: [] | [string];
    displayName: [] | [string];
    avatarUrl: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        username: value.username ? candid_some(value.username) : candid_none(),
        displayName: value.displayName ? candid_some(value.displayName) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
